# Site settings
title: pcRuniversum
email: michalburdukiewicz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A site about PCR and R
baseurl: "/knitr-jekyll"
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  michbur
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
