# Site settings
title: PCRuniversum
email: michalburdukiewicz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A site about PCR and R
baseurl: "/"
url: "http://pcruniversum.github.io/" # the base hostname & protocol for your site
github_username:  PCRuniversum
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
